// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-TOA6VVB0FtX9iLSf181gZ7kP4Y5k_no',
    appId: '1:1059574797005:web:6c7ddf1cbb27bd5577cf84',
    messagingSenderId: '1059574797005',
    projectId: 'pokedex-flutter-d82f9',
    authDomain: 'pokedex-flutter-d82f9.firebaseapp.com',
    storageBucket: 'pokedex-flutter-d82f9.appspot.com',
    measurementId: 'G-NH63VQTVNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYr_rD_mgLGgb0uQ-AGx8ipowI758MYT0',
    appId: '1:1059574797005:android:00438eb3ffcaa9ab77cf84',
    messagingSenderId: '1059574797005',
    projectId: 'pokedex-flutter-d82f9',
    storageBucket: 'pokedex-flutter-d82f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjE1gQ1Oa4Z1_QcbkM6NcvHoQF9uBCQ2A',
    appId: '1:1059574797005:ios:7f95230b6602729d77cf84',
    messagingSenderId: '1059574797005',
    projectId: 'pokedex-flutter-d82f9',
    storageBucket: 'pokedex-flutter-d82f9.appspot.com',
    iosClientId: '1059574797005-hddp7ijfpo152n6iesog2br9nbh05d7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjE1gQ1Oa4Z1_QcbkM6NcvHoQF9uBCQ2A',
    appId: '1:1059574797005:ios:00fe97de99148e3877cf84',
    messagingSenderId: '1059574797005',
    projectId: 'pokedex-flutter-d82f9',
    storageBucket: 'pokedex-flutter-d82f9.appspot.com',
    iosClientId: '1059574797005-7q8gi5kar85klk2oktoi5bo20nrppvit.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
